### ISSUE TITLE
@redmangospros 

### ISSUE THREAD

**Issue by AmazingMech2418** [Mountio/GHStatus#4]
I actually made this. What code did you add? You deceived a Scratch team member into thinking you did any developing of the bot!

**Comment by radioblahaj** [comment]
Sorry, I Edit it

**Comment by AmazingMech2418** [comment]
It's fine. I just don't want you lying since it can make Mountio look bad since you look like you're taking credit for my code in the comment.

**Comment by radioblahaj** [comment]
It's Just, I feel bad, that you're doing everything.
lets make our chat app

**Comment by AmazingMech2418** [comment]
You do the chat app. It's just that I kind of take over during group work...

**Comment by radioblahaj** [comment]
? not don't worry, we can do it together
#mountioStrong
